name: Deploy FastAPI to AWS EC2

# main 브랜치에 코드가 푸시될 때 이 워크플로우를 실행합니다.
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 코드 체크아웃
    - name: Checkout code
      uses: actions/checkout@v2

    # SSH 설정
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # EC2 인스턴스의 호스트 키를 known_hosts에 추가 (보안 강화를 위해 권장)
    - name: Add EC2 to known hosts
      run: |
        ssh-keyscan -H 43.202.241.180 >> ~/.ssh/known_hosts

    # EC2 인스턴스에 SSH로 접속하여 애플리케이션을 배포
    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@43.202.241.180 << 'EOF'
        cd /home/ubuntu/Back-Testing
        git pull origin main
        source venv/bin/activate
        pip install -r requirements.txt
        sudo systemctl restart fastapi
        EOF
